stages:
    - test

before_script:
    - echo "{\"clientId\":\"$GRPC_CLIENT_ID\",\"clientSecret\":\"$GRPC_CLIENT_SECRET\"}" > examples/data/TokenRequest.json
    - cat examples/data/TokenRequest.json

test_csharp:
    image: microsoft/dotnet:latest
    stage: test
    script:
        - cd examples/csharp/GearsSportsApi
        - dotnet restore
        - dotnet build GearsSportsApi/GearsSportsApi.csproj
        - cd GearsSportsApi.Tests
        - dotnet build GearsSportsApi.Tests.csproj
        - dotnet test

test_python:
    image: python:3.6
    stage: test
    script:
        - python -V
        - cd examples/python/gears_sports_api
        - pip install -r requirements.txt
        - python build.py
        - python -m unittest discover -s . --verbose

test_java:
    image: java:8-jdk
    stage: test
    script:
        - java -version
        - cd examples/java/public-api
        - export GRADLE_USER_HOME=`pwd`/.gradle
        - chmod +x gradlew
        - ./gradlew test

test_php:
    image: registry.gitlab.com/gears-sports/web-locker-base:master
    stage: test
    script:
        # Need to download the protoc compiler
        - php -v
        - time apk add git composer make autoconf automake libc-dev g++ linux-headers
        # - time git clone -b $(curl -L https://grpc.io/release) https://github.com/grpc/grpc
        - time git clone -b v1.17.0 https://github.com/grpc/grpc
        - cd grpc
        - time git submodule update --init
        - time make grpc_php_plugin
        - mv bins/opt/grpc_php_plugin ../examples/php/bins/
        - cd ../examples/php
        - time composer install
        - php proto-build.php
        - vendor/bin/phpunit tests
