image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "GearsSportsApi.Tests"

before_script:
    - "apt-get update && apt-get install -y curl gnupg apt-transport-https"
    - "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -"
    - "sh -c 'echo \"deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main\" > /etc/apt/sources.list.d/microsoft.list'"
    - "apt-get update && apt-get install -y powershell"
    - "cd examples/csharp/GearsSportsApi"
    - "dotnet restore"
    - "pwsh generate_protos.bat"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"