image: microsoft/dotnet:latest

stages:
    - build
    - test

variables:
    test: "GearsSportsApi.Tests"

before_script:
    - "cd examples/csharp/GearsSportsApi"
    - "dotnet restore"
    - "generate_protos.bat"

build:
    stage: build
    script:
        - "dotnet build"

test:
    stage: test
    script: 
        - "cd $test"
        - "dotnet test"