stages:
    - test

test_csharp:
    image: microsoft/dotnet:latest
    stage: test
    script:
        - cd examples/csharp/GearsSportsApi
        - dotnet restore
        - dotnet build GearsSportsApi/GearsSportsApi.csproj
        - cd GearsSportsApi.Tests
        - echo "{\"clientId\":\"$GRPC_CLIENT_ID\",\"clientSecret\":\"$GRPC_CLIENT_SECRET\"}" > Data/TokenRequest.json
        - cat Data/TokenRequest.json
        - dotnet build GearsSportsApi.Tests.csproj
        - dotnet test

test_python:
    image: python:3.6
    stage: test
    script:
        - python -V
        - cd examples/python/gears_sports_api
        - pip install -r requirements.txt
        - echo "{\"clientId\":\"$GRPC_CLIENT_ID\",\"clientSecret\":\"$GRPC_CLIENT_SECRET\"}" > test_data/TokenRequest.json
        - python build.py
        - python -m unittest discover -s . --verbose
